"""Add config tables

Revision ID: 84adf20afe0e
Revises: 001
Create Date: 2026-05-02 16:00:30.670964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84adf20afe0e'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Provider 类型'),
    sa.Column('api_key', sa.String(length=500), nullable=False, comment='API Key'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='告警阈值'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='类型: balance/credits'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='项目配置表'
    )
    op.create_table('subscription_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='订阅名称'),
    sa.Column('cycle_type', sa.String(length=20), nullable=True, comment='周期类型'),
    sa.Column('renewal_day', sa.Integer(), nullable=True, comment='续费日'),
    sa.Column('alert_days_before', sa.Integer(), nullable=True, comment='提前告警天数'),
    sa.Column('amount', sa.Float(), nullable=True, comment='订阅金额'),
    sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('last_renewed_date', sa.String(length=20), nullable=True, comment='上次续费日期 (YYYY-MM-DD)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='订阅配置表'
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_config')
    op.drop_table('project_config')
    # ### end Alembic commands ###
